/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankit
 */
public class AddCarPanel extends javax.swing.JPanel {

    private JPanel lowerPanel;
    private CarInformationList carInformationList;

    /**
     * Creates new form AddCarPanel
     */
    public AddCarPanel(JPanel lowerPanel, CarInformationList carInformationList) {
        initComponents();
        this.lowerPanel = lowerPanel;
        this.carInformationList = carInformationList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblMaufacturingYear = new javax.swing.JLabel();
        txtManufacturingYear = new javax.swing.JTextField();
        lblMaxSeats = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        lblMinSeats = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        lblSerialNum = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        lbModelNumber = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblAvailableCity = new javax.swing.JLabel();
        txtAvailableCity = new javax.swing.JTextField();
        lblIsAvailable = new javax.swing.JLabel();
        checkAvailability = new javax.swing.JCheckBox();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        checkMaintenanceCertificate = new javax.swing.JCheckBox();
        lblAddCarHeading = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModel.setText("Model:");

        lblMaufacturingYear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaufacturingYear.setForeground(new java.awt.Color(255, 255, 255));
        lblMaufacturingYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaufacturingYear.setText("Maufacturing Year:");

        lblMaxSeats.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaxSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxSeats.setText("Maximum Seats:");

        lblMinSeats.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMinSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMinSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSeats.setText("Minimum Seats:");

        lblSerialNum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSerialNum.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNum.setText("Serial Number:");

        lbModelNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbModelNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbModelNumber.setText("Model Number:");

        lblAvailableCity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAvailableCity.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailableCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailableCity.setText("Available City:");

        lblIsAvailable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblIsAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblIsAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsAvailable.setText("Availability:");

        checkAvailability.setActionCommand("");

        lblMaintenanceCertificate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaintenanceCertificate.setForeground(new java.awt.Color(255, 255, 255));
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintenanceCertificate.setText("Has Maintenance Certificate Expired:");

        lblAddCarHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddCarHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCarHeading.setText("Add a new Car to the Uber Fleet");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Add ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(13, 13, 13)
                        .addComponent(lblAddCarHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMaxSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMinSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSerialNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAvailableCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbModelNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblMaintenanceCertificate)
                            .addComponent(lblIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaufacturingYear))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkMaintenanceCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtModel)
                                                .addComponent(txtAvailableCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtMaxSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMinSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddCarHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAvailability))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaintenanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkMaintenanceCertificate))
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String model = txtModel.getText().trim();
        String manufacturingYear = txtManufacturingYear.getText().trim();
        String maxSeats = txtMaxSeats.getText().trim();
        String minSeats = txtMinSeats.getText().trim();
        String serialNumber = txtSerialNum.getText().trim();
        String modelNumber = txtModelNumber.getText().trim();
        String availableCity = txtAvailableCity.getText().trim();

        boolean isAvailable = checkAvailability.isSelected();
        boolean hasMaintenanceCErtificate = checkMaintenanceCertificate.isSelected();

        if (model.equals("") || manufacturingYear.equals("") || maxSeats.equals("") || minSeats.equals("") || serialNumber.equals("") || modelNumber.equals("") || availableCity.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            int initialSize = carInformationList.getCarList().size();
            Car car = carInformationList.addCar();
            car.setAvailableCity(availableCity);
            car.setModel(model);
            car.setHasMaintenanceCertificateExpired(hasMaintenanceCErtificate);
            car.setIsAvailable(isAvailable);
            try {
                car.setManufacturedYear(Integer.parseInt(manufacturingYear));
            } catch (NumberFormatException e) {
                carInformationList.getCarList().remove(car);
                JOptionPane.showMessageDialog(null, "Enter only numbers for Manufacturing Year");
            }

            try {
                car.setMaxSeats(Integer.parseInt(maxSeats));
            } catch (NumberFormatException e) {
                carInformationList.getCarList().remove(car);
                JOptionPane.showMessageDialog(null, "Enter only numbers for max number of seats");
            }

            try {
                car.setMinSeats(Integer.parseInt(minSeats));
            } catch (NumberFormatException e) {
                carInformationList.getCarList().remove(car);
                JOptionPane.showMessageDialog(null, "Enter only numbers for min number of seats");
            }

            car.setModelNumber(modelNumber);

            try {
                car.setSerial_num(Integer.parseInt(serialNumber));
            } catch (NumberFormatException e) {
                carInformationList.getCarList().remove(car);
                JOptionPane.showMessageDialog(null, "Enter only numbers for serial number");
            }

            car.setIsAvailable(checkAvailability.isSelected());
            car.setHasMaintenanceCertificateExpired(checkMaintenanceCertificate.isSelected());

            if (carInformationList.getCarList().size() > initialSize) {
                JOptionPane.showMessageDialog(null, "Car Added Successfully");
            }
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        carInformationList.setLastUpdateTime(LocalDateTime.now());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        lowerPanel.remove(this);
        CardLayout layout = (CardLayout) lowerPanel.getLayout();
        layout.previous(lowerPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox checkAvailability;
    private javax.swing.JCheckBox checkMaintenanceCertificate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbModelNumber;
    private javax.swing.JLabel lblAddCarHeading;
    private javax.swing.JLabel lblAvailableCity;
    private javax.swing.JLabel lblIsAvailable;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblMaufacturingYear;
    private javax.swing.JLabel lblMaxSeats;
    private javax.swing.JLabel lblMinSeats;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables
}
