/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.CarInformationList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankit
 */
public class CarManagerPanel extends javax.swing.JPanel {

    private JPanel lowerPanel;
    private CarInformationList carInformationList;

    /**
     * Creates new form ManageCarsPanel
     */
    public CarManagerPanel(JPanel lowerPanel, CarInformationList carInformationList) {
        initComponents();
        this.lowerPanel = lowerPanel;
        this.carInformationList = carInformationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCardDetails = new javax.swing.JButton();
        btnAddCar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        btnManageCardDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageCardDetails.setText("Manage Car Details");
        btnManageCardDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCardDetailsActionPerformed(evt);
            }
        });

        btnAddCar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddCar.setText("Add Car");
        btnAddCar.setActionCommand("Add Car ");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageCardDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageCardDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        
        AddCarPanel addCarPanel = new AddCarPanel(lowerPanel, carInformationList);
        lowerPanel.add("AddCarPanel", addCarPanel);
        CardLayout cardLayout = (CardLayout) lowerPanel.getLayout();
        cardLayout.next(lowerPanel);
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnManageCardDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCardDetailsActionPerformed
         ManageCarDetailsPanel manageCarDetailsPanel = new ManageCarDetailsPanel(lowerPanel, carInformationList);
        lowerPanel.add("ManageCarDetailsPanel", manageCarDetailsPanel);
        CardLayout cardLayout = (CardLayout) lowerPanel.getLayout();
        cardLayout.next(lowerPanel);
    }//GEN-LAST:event_btnManageCardDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnManageCardDetails;
    // End of variables declaration//GEN-END:variables
}
