/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ankit
 */
public class ViewCarDetailsPanel extends javax.swing.JPanel {

    private JPanel lowerPanel;
    private Car car;
    private CarInformationList carInformationList;

    /**
     * Creates new form ViewCarDetailsPanel
     */
    public ViewCarDetailsPanel(JPanel lowerPanel, Car car, CarInformationList carInformationList) {
        initComponents();
        this.lowerPanel = lowerPanel;
        this.car = car;
        this.carInformationList = carInformationList;

        chkHasMainCertExp.setVisible(false);
        chkIsAvailable.setVisible(false);
        viewDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbModelNumber = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblAvailableCity = new javax.swing.JLabel();
        lblMaufacturingYear = new javax.swing.JLabel();
        txtAvailableCity = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        lblIsAvailable = new javax.swing.JLabel();
        lblMaxSeats = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        lblMinSeats = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        lblSerialNum = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        lblViewCarDetails = new javax.swing.JLabel();
        txtMaintenanceCertificate = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        chkHasMainCertExp = new javax.swing.JCheckBox();
        chkIsAvailable = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 0, 0));

        lbModelNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbModelNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbModelNumber.setText("Model Number:");

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModel.setText("Model:");

        txtModelNumber.setEnabled(false);

        txtModel.setEnabled(false);

        lblAvailableCity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAvailableCity.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailableCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailableCity.setText("Available City:");

        lblMaufacturingYear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaufacturingYear.setForeground(new java.awt.Color(255, 255, 255));
        lblMaufacturingYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaufacturingYear.setText("Maufacturing Year:");

        txtAvailableCity.setEnabled(false);

        txtManufacturingYear.setEnabled(false);

        lblIsAvailable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblIsAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblIsAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsAvailable.setText("Availability:");

        lblMaxSeats.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaxSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxSeats.setText("Maximum Seats:");

        txtMaxSeats.setEnabled(false);

        lblMinSeats.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMinSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMinSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinSeats.setText("Minimum Seats:");

        lblMaintenanceCertificate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaintenanceCertificate.setForeground(new java.awt.Color(255, 255, 255));
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintenanceCertificate.setText("Has Maintenance Certificate Expired:");

        txtMinSeats.setEnabled(false);

        lblSerialNum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSerialNum.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNum.setText("Serial Number:");

        txtSerialNum.setEnabled(false);

        lblViewCarDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblViewCarDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCarDetails.setText("View Car Details");

        txtMaintenanceCertificate.setEnabled(false);

        txtAvailability.setEnabled(false);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        chkHasMainCertExp.setBackground(new java.awt.Color(255, 102, 204));
        chkHasMainCertExp.setForeground(new java.awt.Color(255, 255, 255));

        chkIsAvailable.setBackground(new java.awt.Color(153, 255, 153));
        chkIsAvailable.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(75, 75, 75)
                .addComponent(lblViewCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(lblIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblMaufacturingYear)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(chkIsAvailable))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHasMainCertExp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtModel)
                                        .addComponent(txtAvailableCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtMinSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMaintenanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkIsAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHasMainCertExp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaintenanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaintenanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
        lowerPanel.remove(this);
        
        CardLayout layout = (CardLayout) lowerPanel.getLayout();
        Component[] comps = lowerPanel.getComponents();
        for (Component component : comps) {
            if (component instanceof ManageCarDetailsPanel) {
                ManageCarDetailsPanel manageCarDetailsPanel = (ManageCarDetailsPanel) component;
                manageCarDetailsPanel.populateTable(carInformationList.getCarList());
                manageCarDetailsPanel.populateUpdateDatTime(carInformationList);
            }
        }
        
        layout.previous(lowerPanel);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtAvailability.setVisible(false);
        txtAvailableCity.setEnabled(true);
        txtMaintenanceCertificate.setVisible(false);
        txtManufacturingYear.setEnabled(true);
        txtMaxSeats.setEnabled(true);
        txtMinSeats.setEnabled(true);
        txtModel.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtSerialNum.setEnabled(true);

        chkIsAvailable.setVisible(true);
        chkHasMainCertExp.setVisible(true);

        if (txtAvailability.getText().equalsIgnoreCase("yes")) {
            chkIsAvailable.setSelected(true);
        } else {
            chkIsAvailable.setSelected(false);
        }
        if (txtMaintenanceCertificate.getText().equalsIgnoreCase("yes")) {
            chkHasMainCertExp.setSelected(true);
        } else {
            chkHasMainCertExp.setSelected(false);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

        txtAvailability.setVisible(true);
        txtMaintenanceCertificate.setVisible(true);

        chkHasMainCertExp.setVisible(false);
        chkIsAvailable.setVisible(false);

        txtAvailability.setEnabled(false);
        txtAvailableCity.setEnabled(false);
        txtMaintenanceCertificate.setEnabled(false);
        txtManufacturingYear.setEnabled(false);
        txtMaxSeats.setEnabled(false);
        txtMinSeats.setEnabled(false);
        txtModel.setEnabled(false);
        txtModelNumber.setEnabled(false);
        txtSerialNum.setEnabled(false);

        if (chkHasMainCertExp.isSelected()) {
            txtMaintenanceCertificate.setText("Yes");
        } else {
            txtMaintenanceCertificate.setText("No");
        }

        if (chkIsAvailable.isSelected()) {
            txtAvailability.setText("Yes");
        } else {
            txtAvailability.setText("No");
        }

        car.setIsAvailable(chkIsAvailable.isSelected());
        car.setAvailableCity(txtAvailableCity.getText());
        car.setHasMaintenanceCertificateExpired(chkHasMainCertExp.isSelected());
        try {

            car.setManufacturedYear(Integer.parseInt(txtManufacturingYear.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid year");
        }

        try {
            car.setMaxSeats(Integer.parseInt(txtMaxSeats.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid number of seats");
        }

        try {
            car.setMinSeats(Integer.parseInt(txtMinSeats.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid number of seats");
        }

        try {
            car.setSerial_num(Integer.parseInt(txtSerialNum.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid number of serial number");
        }

        car.setModel(txtModel.getText());
        car.setModelNumber(txtModelNumber.getText());
        
        carInformationList.setLastUpdateTime(LocalDateTime.now());
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkHasMainCertExp;
    private javax.swing.JCheckBox chkIsAvailable;
    private javax.swing.JLabel lbModelNumber;
    private javax.swing.JLabel lblAvailableCity;
    private javax.swing.JLabel lblIsAvailable;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblMaufacturingYear;
    private javax.swing.JLabel lblMaxSeats;
    private javax.swing.JLabel lblMinSeats;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JLabel lblViewCarDetails;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtMaintenanceCertificate;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables

    private void viewDetails() {
        txtAvailability.setText(car.isIsAvailable() ? "Yes" : "No");
        txtAvailableCity.setText(car.getAvailableCity());
        txtMaintenanceCertificate.setText(car.hasMaintenanceCertificateExpired() ? "Yes" : "No");
        txtManufacturingYear.setText(String.valueOf(car.getManufacturedYear()));
        txtMaxSeats.setText(String.valueOf(car.getMaxSeats()));
        txtMinSeats.setText(String.valueOf(car.getMinSeats()));
        txtModel.setText(car.getModel());
        txtModelNumber.setText(car.getModelNumber());
        txtSerialNum.setText(String.valueOf(car.getSerial_num()));

        btnSave.setEnabled(false);
    }
}
